"""add fields to diary_records

Revision ID: 4c1be3bb50f6
Revises: 610f4b4f3399
Create Date: 2025-05-28 08:59:50.838227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1be3bb50f6'
down_revision: Union[str, None] = '610f4b4f3399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_records', sa.Column('mood', sa.String(), nullable=True))
    op.add_column('diary_records', sa.Column('mood_mark', sa.Integer(), nullable=True))
    op.add_column('diary_records', sa.Column('health', sa.String(), nullable=True))
    op.add_column('diary_records', sa.Column('health_mark', sa.Integer(), nullable=True))
    op.add_column('diary_records', sa.Column('health_reason', sa.String(), nullable=True))
    op.add_column('diary_records', sa.Column('weather', sa.String(), nullable=True))
    op.add_column('diary_records', sa.Column('illness', sa.String(), nullable=True))
    op.add_column('diary_records', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary_records', 'summary')
    op.drop_column('diary_records', 'illness')
    op.drop_column('diary_records', 'weather')
    op.drop_column('diary_records', 'health_reason')
    op.drop_column('diary_records', 'health_mark')
    op.drop_column('diary_records', 'health')
    op.drop_column('diary_records', 'mood_mark')
    op.drop_column('diary_records', 'mood')
    # ### end Alembic commands ###
