"""create sleeps

Revision ID: 610f4b4f3399
Revises: a080bf5cd9c9
Create Date: 2025-05-26 20:32:54.711860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610f4b4f3399'
down_revision: Union[str, None] = 'a080bf5cd9c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleeps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deep_sleep_time', sa.Integer(), nullable=True),
    sa.Column('shallow_sleep_time', sa.Integer(), nullable=True),
    sa.Column('rem_time', sa.Integer(), nullable=True),
    sa.Column('total_sleep_time', sa.Integer(), nullable=False),
    sa.Column('wake_time', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('naps', sa.Integer(), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleeps')
    # ### end Alembic commands ###
